### ISSUE TITLE
Feature: User can start adventure

### ISSUE THREAD

**Issue by BlakexLim** [BlakexLim/Shield-Knight#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can start a new adventure or continue an existing adventure.
Limited to 4 saved slots.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

- On the landing page user will:
  - Be able to login or play as a guest
  - Then user will be redirected to the new game screen (if first time logged in)
  - New game screen will have previous saved adventures of current user
  - User clicks new game to start

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="460" alt="LandingPage ShieldKnight" src="https://github.com/BlakexLim/Shield-Knight/assets/132517914/f8b72262-bc40-4419-9933-3163d9e68d05">
<img width="467" alt="shieldKnight NewGame" src="https://github.com/BlakexLim/Shield-Knight/assets/132517914/22adca78-4690-4f1b-88af-b80e1ad33b30">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Test path to add a new user with HTTPie
- [x] Test path to retrieve user with HTTPie

### ☁️ Server Tasks

- [x] Update `server.js` to add a new middleware:
  - [x] Fetch Landing page
  - [x] Fetch New Game page
  - [x] Fetch Controls & Objectives page
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a parent component
- [x] Create a component for New account
  - [x] Generate input fields for username and password 
  - [x] Generate button `Create account` 
- [x] Create a component for User login
  - [x] Generate input fields for username and password
  - [x] Generate button `Login` 
  - [x] Generate button `Continue as guest` that redirects user to Controls & Objectives page
- [x] Create a component for the Controls & Objectives page
  - [x] Generate information that shows the controls and objectives to the user 
  - [x] Generate a button `Start` that takes user to Game Map  
- [x] Create a component for New Game page
  - [x] Generate a button `New Game` that will take user to Controls & Objectives page 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
