### ISSUE TITLE
Feature: User can navigate with keys

### ISSUE THREAD

**Issue by BlakexLim** [BlakexLim/Shield-Knight#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can navigate a character on map with designated keys
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user presses the `arrow` or `w` `a` `s` `d` keys a character on screen will respond to each key pressed.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="461" alt="Screenshot 2024-04-19 110155" src="https://github.com/BlakexLim/Shield-Knight/assets/132517914/6035323c-85e8-420e-a476-335883029996">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to render a map 
- [x] Create a component to render hero character
- [x] Create a component called `Movement`
  - [x] add an event listener on window for keydown events
    - [x] this will call a function in the component that controls hero movement
    - [x] access hero's state to grab current x and y 
    - [x] Hero should be contrained within the map

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
